### ISSUE TITLE
Install problem

### ISSUE THREAD

**Issue by EMHmark7** [Herteby/grapher-vue-demo#4]
meteor npm install generates errors. Please let me know if you cannot reproduce the error, I could send the log. Thanks. Marc

**Comment by Herteby** [comment]
Yeah you'll definitely have to send the log if I'm going to be able to help you with anything. I tested it myself a few days ago and it worked for me.

**Comment by EMHmark7** [comment]
[2018-07-09T15_54_03_003Z-debug.log](https://github.com/Herteby/graphical-grapher-demo/files/2177028/2018-07-09T15_54_03_003Z-debug.log)

**Comment by Herteby** [comment]
I don't know, looks like a strange issue with NPM. I don't think it's an issue with this project.
Try googling "npm Error: write after end", or maybe just try running it again or something.

**Comment by EMHmark7** [comment]
Some people say for their own problem it could be a NPM version with bugs. My system says NPM is not installed. I suppose it is within the Meteor installation. I did what you said; Repeat the line. it worked. But when doing meteor, the app runs, but I got:
...
=> [HMR] Dev server listening on port 3003.
W20180709-12:32:47.522(-4)? (STDERR) The `stylus` package has been deprecated.
W20180709-12:32:47.600(-4)? (STDERR) 
W20180709-12:32:47.601(-4)? (STDERR) To continue using the last supported version
W20180709-12:32:47.601(-4)? (STDERR) of this package, pin your package version to
W20180709-12:32:47.601(-4)? (STDERR) 2.513.14 (`meteor add stylus@=2.513.14`).
W20180709-12:32:47.602(-4)? (STDERR) Note: you are using a pure-JavaScript implementation of bcrypt.
W20180709-12:32:47.602(-4)? (STDERR) While this implementation will work correctly, it is known to be
W20180709-12:32:47.602(-4)? (STDERR) approximately three times slower than the native implementation.
W20180709-12:32:47.602(-4)? (STDERR) In order to use the native implementation instead, run
W20180709-12:32:47.602(-4)? (STDERR) 
W20180709-12:32:47.603(-4)? (STDERR)   meteor npm install --save bcrypt
W20180709-12:32:47.603(-4)? (STDERR) 
W20180709-12:32:47.603(-4)? (STDERR) in the root directory of your application.
I20180709-12:33:03.259(-4)? [ok] fixtures have been loaded.
=> Started your app.

=> App running at: http://localhost:3000/
----------------------------------------------------////////////////////////////////////////////////////////////////////
doing  meteor npm install --save bcrypt
generated many errors, but the app works:
> bcrypt@3.0.0 install /home/marc/vm/graphical-grapher-demo/node_modules/bcrypt
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Tried to download(404): https://github.com/kelektiv/node.bcrypt.js/releases/download/v3.0.0/bcrypt_lib-v3.0.0-node-v57-linux-x64-glibc.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for bcrypt@3.0.0 and node@8.8.1 (node-v57 ABI, glibc) (falling back to source compile with node-gyp) 
make: Entering directory '/home/marc/vm/graphical-grapher-demo/node_modules/bcrypt/build'
  CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
make: g++: Command not found
bcrypt_lib.target.mk:97: recipe for target 'Release/obj.target/bcrypt_lib/src/blowfish.o' failed
make: *** [Release/obj.target/bcrypt_lib/src/blowfish.o] Error 127
make: Leaving directory '/home/marc/vm/graphical-grapher-demo/node_modules/bcrypt/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/marc/.meteor/packages/meteor-tool/.1.6.0.g2theb.mfn5d++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.10.0-38-generic
gyp ERR! command "/home/marc/.meteor/packages/meteor-tool/.1.6.0.g2theb.mfn5d++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node" "/home/marc/.meteor/packages/meteor-tool/.1.6.0.g2theb.mfn5d++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/marc/vm/graphical-grapher-demo/node_modules/bcrypt/lib/binding/bcrypt_lib.node" "--module_name=bcrypt_lib" "--module_path=/home/marc/vm/graphical-grapher-demo/node_modules/bcrypt/lib/binding" "--napi_version=1" "--node_abi_napi=napi"
gyp ERR! cwd /home/marc/vm/graphical-grapher-demo/node_modules/bcrypt
gyp ERR! node -v v8.8.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/home/marc/.meteor/packages/meteor-tool/.1.6.0.g2theb.mfn5d++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node /home/marc/.meteor/packages/meteor-tool/.1.6.0.g2theb.mfn5d++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/marc/vm/graphical-grapher-demo/node_modules/bcrypt/lib/binding/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/home/marc/vm/graphical-grapher-demo/node_modules/bcrypt/lib/binding --napi_version=1 --node_abi_napi=napi' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/marc/vm/graphical-grapher-demo/node_modules/bcrypt/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:125:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:927:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Linux 4.10.0-38-generic
node-pre-gyp ERR! command "/home/marc/.meteor/packages/meteor-tool/.1.6.0.g2theb.mfn5d++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node" "/home/marc/vm/graphical-grapher-demo/node_modules/bcrypt/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/marc/vm/graphical-grapher-demo/node_modules/bcrypt
node-pre-gyp ERR! node -v v8.8.1
node-pre-gyp ERR! node-pre-gyp -v v0.10.2
node-pre-gyp ERR! not ok 
Failed to execute '/home/marc/.meteor/packages/meteor-tool/.1.6.0.g2theb.mfn5d++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node /home/marc/.meteor/packages/meteor-tool/.1.6.0.g2theb.mfn5d++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/marc/vm/graphical-grapher-demo/node_modules/bcrypt/lib/binding/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/home/marc/vm/graphical-grapher-demo/node_modules/bcrypt/lib/binding --napi_version=1 --node_abi_napi=napi' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bcrypt@3.0.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bcrypt@3.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/marc/.npm/_logs/2018-07-09T16_40_14_865Z-debug.log
